### ISSUE TITLE
PCB images

### ISSUE THREAD

**Issue by ellisgl** [JeremyJStarcher/Goldfish-clone-JLCPCB#1]
May we have some PCB images (KiCAD / 3D view) in the docs?

**Comment by JeremyJStarcher** [comment]
I'll put those in docs shortly ... I'm making some last minute tweaks before sending the board in.

**Comment by JeremyJStarcher** [comment]
Pictures added...
I'm ready to upload all the files to JLCPCB but they are out of the ATMega32u4's in that footprint. :(
